Repository Fchat-Horizon/Horizon, pull requests merged in 2025-05, with the labels that each got.

#75 fix: Remove unnecessary include line from tsconfig
  tsconfig.json
Labels: development

#122 Fixes Windows notifications being stinky poopoo
  electron/main.ts
  electron/notifications.ts
  electron/package.json
Labels: bug

#129 Changes Prettier pre-commit hook to check instead of write
  .github/workflows/pr-build.yml
  .husky/pre-commit
  package.json
Labels: Quality of Life, development

#43 Adds automatic update check
  chat/localize.ts
  electron/Window.vue
  electron/main.ts
Labels: enhancement

#88 feature: Gender markers beside names
  chat/CharacterSearch.vue
  chat/ConversationView.vue
  chat/RecentConversations.vue
  chat/SettingsView.vue
  chat/UserList.vue
  chat/UserView.vue
  chat/bbcode.ts
  chat/character/CharacterAdView.vue
  chat/character/CharacterChannelList.vue
  chat/common.ts
  chat/interfaces.ts
  chat/message_view.ts
Labels: enhancement

#82 fix: Check if logged in before fetching character-specific settings
  chat/UserView.vue
  chat/message_view.ts
Labels: bug

#120 1.31.0 Pre-release build
  .github/workflows/pr-build.yml
  .gitignore
  .husky/pre-commit
  .prettierignore
  CHANGELOG.md
  README.md
  bbcode/editor.ts
  chat/CharacterSearch.vue
  chat/Chat.vue
  chat/ChatView.vue
  chat/ConversationView.vue
  chat/PmPartnerAdder.vue
  chat/RecentConversations.vue
  chat/SettingsView.vue
  chat/UserList.vue
  chat/UserView.vue
  chat/assets/silence.mp3
  chat/assets/silence.ogg
  chat/assets/silence.wav
  chat/bbcode.ts
  chat/character/CharacterAdView.vue
  chat/character/CharacterChannelList.vue
  chat/common.ts
  chat/conversations.ts
  chat/interfaces.ts
  chat/localize.ts
  chat/message_view.ts
  chat/preview/event-bus.ts
  chat/slash_commands.ts
  electron/Index.vue
  electron/Window.vue
  electron/chat.ts
  electron/main.ts
  electron/notifications.ts
  electron/package.json
  learn/filter/types.ts
  package.json
  scss/_chat.scss
  scss/themes/chat/dracula.scss
  scss/themes/variables/_dracula_variables.scss
  tsconfig.json
Labels: do not merge, development

#139 1.31.0 Release
  .github/workflows/pr-build.yml
  .gitignore
  .husky/pre-commit
  .prettierignore
  CHANGELOG.md
  README.md
  bbcode/editor.ts
  chat/CharacterSearch.vue
  chat/Chat.vue
  chat/ChatView.vue
  chat/ConversationView.vue
  chat/PmPartnerAdder.vue
  chat/RecentConversations.vue
  chat/SettingsView.vue
  chat/UserList.vue
  chat/UserView.vue
  chat/assets/silence.mp3
  chat/assets/silence.ogg
  chat/assets/silence.wav
  chat/bbcode.ts
  chat/character/CharacterAdView.vue
  chat/character/CharacterChannelList.vue
  chat/common.ts
  chat/conversations.ts
  chat/interfaces.ts
  chat/localize.ts
  chat/message_view.ts
  chat/preview/event-bus.ts
  chat/slash_commands.ts
  electron/Index.vue
  electron/Window.vue
  electron/chat.ts
  electron/main.ts
  electron/notifications.ts
  electron/package.json
  learn/filter/types.ts
  package.json
  scss/_chat.scss
  scss/themes/chat/dracula.scss
  scss/themes/variables/_dracula_variables.scss
  tsconfig.json
Labels: development

#178 Adds extra channel navigation shortcuts
  chat/ChatView.vue
Labels: feature, Quality of Life

#142 Implement imgchest.com as a High-Quality Portrait domain
  PRIVACY.md
  electron/index.html
  electron/window.html
  learn/profile-cache.ts
  learn/recommend/profile-recommendation.ts
Labels: enhancement, Quality of Life

#128 Implement proxy settings
  chat/localize.ts
  electron/Index.vue
  electron/common.ts
  electron/main.ts
Labels: feature

#179 1.31.1 Pre-release build
  CHANGELOG.md
  CONTRIBUTING.md
  PRIVACY.md
  README.md
  bbcode/Editor.vue
  bbcode/editor.ts
  bump_version.sh
  chat/ChatView.vue
  chat/PmPartnerAdder.vue
  chat/UserMenu.vue
  chat/localize.ts
  chat/preview/event-bus.ts
  chat/slash_commands.ts
  electron/Index.vue
  electron/chat.ts
  electron/common.ts
  electron/index.html
  electron/main.ts
  electron/package.json
  electron/window.html
  learn/profile-cache.ts
  learn/recommend/profile-recommendation.ts
  package.json
  pnpm-lock.yaml
  scss/package.json
  scss/pnpm-lock.yaml
  site/character_page/character_page.vue
  site/character_page/memo_dialog.vue
Labels: development
