Repository Fchat-Horizon/Horizon, pull requests merged in 2025-04, with the labels that each got.

#106 fix: Channel message lag
  chat/ChatView.vue
Labels: Quality of Life

#79 docs: Fix broken linux download links
  README.md
Labels: documentation

#118 Fixes .dmg icon positions
  electron/package.json
Labels: styling

#114 1.30.3 Release
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/docs.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
  .github/ISSUE_TEMPLATE/styling.md
  .github/workflows/pr-build.yml
  CHANGELOG.md
  README.md
  chat/ChatView.vue
  chat/conversations.ts
  docs/images/macos-whitelist-ctrl-open.png
  docs/images/macos-whitelist-settings.png
  electron/main.ts
  electron/package.json
  electron/pnpm-lock.yaml
  package.json
  pnpm-lock.yaml
Labels: development

#101 Brings MacOS devtools shortcut in line with platform's expectations
  electron/chat.ts
Labels: Quality of Life, development

#98 Fixes two more Dracula colors after the SCSS refactor
  scss/themes/chat/dracula.scss
  scss/themes/variables/_dracula_variables.scss
Labels: styling

#53 Updates .gitignore for new release scripts
  .gitignore
  .prettierignore
Labels: development

#89 Fixes window padding not adjusting when (un)maximizing the window
  electron/Window.vue
Labels: bug

#100 Makes conversation list status icons consistent w/ user list
  chat/ChatView.vue
Labels: Quality of Life, styling

#95 fix: Listeners are not properly removed when logging out
  chat/ChatView.vue
Labels: bug

#72 fix: Duplicate event listeners
  chat/preview/event-bus.ts
  electron/Index.vue
Labels: bug
